version: "3.7"

services:
  solid-server:
    image: solidproject/community-server:latest
    ports:
      - "3000:3000"
    volumes:
      - ~/Solid:/data

  client-app:
    build: .
    image: client
    volumes:
      - ./node_modules:/client/node_modules
      - ./app:/client/app
    working_dir: /client
    ports:
      - "3001:1234"
    stdin_open: true
    tty: true
