version: "3.7"

services:
  solid-server:
    image: solidproject/community-server:latest
    ports:
      - "3000:3000"
    volumes:
      - ~/Solid:/data

  barking-permit-app:
    build: .
    image: barking-permit
    volumes:
      - ./node_modules:/barking-permit/node_modules
      - ./app:/barking-permit/app
    working_dir: /barking-permit
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
